import Head from "next/head";
import MathGame from "../components/ui/mathgame";
import Navbar from "../components/ui/navbar";
import { useState } from "react";
import Scoreboard from "../components/ui/scoreboard";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const [playerName, setPlayerName] = useState("");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <div className="flex min-h-screen flex-col items-center justify-between p-24">
          <div>
            <MathGame playerName={playerName} setPlayerName={setPlayerName} />
          </div>
        </div>
      </div>
    </>
  );
}
